// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3Cq1AlvhimeFIq2CNeyKGwlaVChGiGb4',
    appId: '1:1022532656951:web:344818775670f7350d84b2',
    messagingSenderId: '1022532656951',
    projectId: 'tilbil-92a49',
    authDomain: 'tilbil-92a49.firebaseapp.com',
    storageBucket: 'tilbil-92a49.appspot.com',
    measurementId: 'G-9ETJ40K0QL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMlzgRfUdeIU8jHvjtjtURtKIyDjWBKcA',
    appId: '1:1022532656951:android:8a684b648e8fd98b0d84b2',
    messagingSenderId: '1022532656951',
    projectId: 'tilbil-92a49',
    storageBucket: 'tilbil-92a49.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqY0QitkNOm_IVeS8wKftopun2xPqm3nU',
    appId: '1:1022532656951:ios:a5b8c5919395d6910d84b2',
    messagingSenderId: '1022532656951',
    projectId: 'tilbil-92a49',
    storageBucket: 'tilbil-92a49.appspot.com',
    iosClientId:
        '1022532656951-nn1jktcda28h8f4hfdjeb7mjrbbjqqek.apps.googleusercontent.com',
    iosBundleId: 'com.tilbil.org.tilbil',
  );
}
